version: "3.8"
services:
  proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_HOST: '${DATABASE_HOST}'
      MYSQL_TCP_PORT: '${DATABASE_PORT}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DATABASE_USERNAME}", "-p${DATABASE_PASSWORD}", "-h${DATABASE_HOST}", "-P${DATABASE_PORT}", "ping"]
      retries: 3
      timeout: 5s
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      app:
        ipv4_address: 10.6.0.3

  web:
    build: ./packages/web
    restart: always
    volumes:
      - ./packages/web:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      app:
        ipv4_address: 10.6.0.4

  core:
    build: ./packages/core
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    volumes:
      - uploads:/app/public
      - ./packages/core:/app
    env_file:
      - .env

    ports:
      - 1337:1337
    networks:
      app:
        ipv4_address: 10.6.0.5

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ./docker-volume/database
      o: bind
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ./docker-volume/uploads
      o: bind